version: "3.8"

services:
  frontend:
    image: httpd:2.4
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./resources:/usr/local/apache2/htdocs
    environment:
      - APACHE_DOCUMENT_ROOT=/usr/local/apache2/htdocs
    networks:
      - network

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: u1
      POSTGRES_PASSWORD: u1
    ports:
      - "5432:5432"
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U u1 -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network

volumes:
  db_data_postgres:

networks:
  network:
    driver: bridge